### PR TITLE
fix(aliases): rollback to initialize root command with correct aliases

### LINKED ISSUE #25: command aliases are not being registered in the first registration of the parent command
The code below the source-code calls for the register method of the CommandMap due to fixing the correct position of the root command.
https://github.com/saiintbrisson/command-framework/blob/ad6ed18e914f7cf1f2ae2c9ef0d0e3f7e2d39f31/bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java#L145

However, instead of fixing the correct position of the root command, it just allows the aliases to not work, as the default implementation of `BukkitCommand` doesn't include the correct command aliases of `CommandInfo`, so it's empty when it should be registered from `CommandMap`:
image

### PR DESCRIPTION
**Pull request by luiz-otavio**
Bla bla bla

### CODE REVIEW

**Comment by saiintbrisson** [comment]
Fixes #25.

File: bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java [hunk 1]
```diff
@@ -148,8 +150,31 @@ public BukkitCommand getCommand(String name) {
         return subCommand.createRecursive(name);
     }
 
+    // Due to the fact that the above method isn't good for registering commands with multiple aliases, I've added this method.
```
Comment (saiintbrisson) [inline bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java]: Remove this comment.

**Review by saiintbrisson — CHANGES_REQUESTED** [review]

File: bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java [hunk 2]
```diff
@@ -148,8 +150,31 @@ public BukkitCommand getCommand(String name) {
...
+    private BukkitCommand getCommand(String name, Consumer<BukkitCommand> whenComplete) {
```
Comment (saiintbrisson) [inline bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java]:
```suggestion
    private BukkitCommand getOrRegisterCommand(String name, Consumer<BukkitCommand> onRegister) {
```

File: bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java [hunk 3]
```diff
@@ -148,8 +150,31 @@ public BukkitCommand getCommand(String name) {
...
+            subCommand = new BukkitCommand(this, nextSubCommand, 0);
+            whenComplete.accept(subCommand);
+            commandMap.put(nextSubCommand, subCommand);
+        }
+
+        if (subCommand.getPosition() == 0) {
+            bukkitCommandMap.register(plugin.getName(), subCommand);
+        }
+
+        return subCommand.createRecursive(name);
```
Comment (saiintbrisson) [inline bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java]:
```suggestion
        String[] segments = name.split(".");
        String root = segments[0];

        BukkitCommand command = commandMap.get(root);
        if (command == null) {
            command = new BukkitCommand(this, root, 0);
            commandMap.put(root, command);
            
            if (segments.length > 1) {
                bukkitCommandMap.register(plugin.getName(), command);
            }
        }
        
        command = command.createRecursive(name);
        whenComplete.accept(command);

        if (command.getPosition() == 0) {
            bukkitCommandMap.register(plugin.getName(), command);
        }

        return command;
```

File: bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java [hunk 4]
```diff
@@ -173,27 +198,29 @@ public void registerCommands(Object... objects) {
...
-            return;
-        }
+        final BukkitCommand recursive = getCommand(name, command -> {
+            command.initCompleter(completerExecutor);
+        });
 
-        recursive.initCompleter(completerExecutor);
+        if (recursive != null) {
+            recursive.initCompleter(completerExecutor);
+        }
```
Comment (saiintbrisson) [inline bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java]: Same here.

**Review by saiintbrisson — CHANGES_REQUESTED** [review]

File: bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java [hunk 5]
```diff
@@ -148,8 +151,36 @@ public BukkitCommand getCommand(String name) {
         return subCommand.createRecursive(name);
     }
 
+    private void getOrRegisterCommand(String name, Consumer<BukkitCommand> whenComplete) {
```
Comment (saiintbrisson) [inline bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java]:
```suggestion
    private BukkitCommand getOrRegisterCommand(String name, Consumer<BukkitCommand> whenComplete) {
```

**Review by saiintbrisson — CHANGES_REQUESTED** [review]

File: bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java [hunk 6]
```diff
@@ -148,8 +151,36 @@ public BukkitCommand getCommand(String name) {
...
+        int index = name.indexOf('.');
+        String nextSubCommand = name;
+        if (index != -1) {
+            nextSubCommand = name.substring(0, index);
+        }
```
Comment (saiintbrisson) [inline bukkit/src/main/java/me/saiintbrisson/bukkit/command/BukkitFrame.java]: Not used.

**Review by saiintbrisson — COMMENTED** [review]
You can call `getOrRegisterCommand` from within `getCommand`, passing an empty consumer.

**Review by saiintbrisson — APPROVED** [review]

**Comment by saiintbrisson** [comment]
si

**Comment by saiintbrisson** [comment]
@devwckd
